### ISSUE TITLE
Preferences - command to read setting descriptions

### ISSUE THREAD

**Issue by kara-louise** [jcsteh/osara#103]
When you move the mouse over an option in REAPER's preferences dialogue, a short description of it's function appears at the bottom of the window. Eg. "Choose language from installed languages (you must quit and restart REAPER for language changes to take effect." is displayed when you move the mouse over the language combo box. Unfortunately, the text does not update when you use tab or shift tab to navigate through the dialogue.
It is possible to use NVDA's Move Mouse To Navigator Object command to refresh it then find the object with Object nav, but it's not at all intuitive to do this. Furthermore, the text might be visually displayed at the bottom of the dialogue, but the object containing the text is higher up the tree next to the find button, so the read bottom line of window command doesn't work. Also descriptions are usually more than one line.

So, to make this easier for the user, you could have a command that will move the mouse to the currently focused control, locate the object containing the description, read it then move the mouse back to the focused control.
This is a very crude way of doing it which would probably only work with NVDA. There's probably a far more elegant method of accomplishing this so that it'll be compatible with all screen readers but I'm not sure what it would be.
Below is the developer info of the object where the descriptive text is displayed. I'll be happy to provide more info if required.

Developer info for navigator object:
name: u'Choose language from installed languages (you must quit and restart REAPER for language changes to take effect.'
role: ROLE_STATICTEXT
states: STATE_READONLY
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.StaticText object at 0x052C7930>
Python class mro: (<class 'NVDAObjects.IAccessible.StaticText'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (299, 565, 345, 23)
value: None
appModule: <'appModuleHandler' (appName u'reaper', process ID 32) at address 52460f0>
appModule.productName: u'REAPER'
appModule.productVersion: u'5.32'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 3146962L
windowClassName: u'Static'
windowControlID: 1259
windowStyle: 1342308352
windowThreadID: 3752
windowText: u'Choose language from installed languages (you must quit and restart REAPER for language changes to take effect.'
displayText: u'Choose language from installed languages (you must quit and restart REAPER forlanguage changes to take effect.'
IAccessibleObject: <POINTER(IAccessible) ptr=0x7cfdbf0 at 509ecb0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=3146962L, objectID=-4, childID=0L
IAccessible accName: u'Choose language from installed languages (you must quit and restart REAPER for language changes to take effect.'
IAccessible accRole: ROLE_SYSTEM_STATICTEXT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_VALID (64)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by jcsteh** [comment]
Ideally, I think REAPER would expose the tool tips on each control as the accDescription (using MSAA dynamic annotation) without the user needing to mouse over the control. Failing that, this could probably be hacked together in OSARA. The idea would be to watch for focus changes (we already have handleWinEvent for this), check if they're in the preferences dialog, move the mouse to the control, find the tip window, grab the tip text, and finally use MSAA dynamic annotation to annotate the accDescription for the focus.

**Comment by jcsteh** [comment]
Note that the above would only work on Windows. I don't think we could manage this on Mac, or at least, I don't know how.

**Comment by pitermach** [comment]
The mac has something similar to the description attribute you described. VoiceOver calls them help tags, and you can have VO read out a help tag with a hotkey or they can be spoken after a delay. I don’t know if in the accessibility API’s those would be named help tags, descriptions or hints (which is what they’re called on iOS) but Cockos would probably be able to do a similar thing for both platforms.

**Comment by jcsteh** [comment]
Oh sure; Cockos could definitely do it for Mac. I meant that if we do this
in OSARA, it's not possible for us to get at and hack those things.

**Comment by ScottChesworth** [comment]
Do you wanna ask Cockos @jcsteh , or should I?

**Comment by jcsteh** [comment]
I just stayed up way too late implementing this in OSARA, Windows only. It'd probably be better for Cockos to do it, but it was an interesting technical challenge which tickled me for some reason.

@ScottChesworth, it'd probably still be good to take this up with Cockos because it'd be nicer done in REAPER and so it'd work on the Mac. If they implement it, I can remove my hack. Please go ahead and pursue this with them if you have time. :)

**Comment by ScottChesworth** [comment]
Possibly a daft question but, how do I use your implementation? Is there a keystroke to read these tips?

I've just written in to Cockos with notes compiled from this thread. Let's see what happens.

Oh, and thanks for staying up late! 👍

**Comment by jcsteh** [comment]
It should just get reported when you tab through the dialog. You need to
have NVDA's report object descriptions setting turned on.

**Comment by ScottChesworth** [comment]
I have "Report object descriptions" checked. Not hearing anything extra here yet though. Any idea what might be up?

**Comment by jcsteh** [comment]
No idea. I was testing with 32 bit, so I just tested with 64 bit to see if
that made a difference, but both work fine for me here. Can you try with a
clean config?

**Comment by ScottChesworth** [comment]
Turns out I'd accidentally installed the new snapshot to the UserPlugins directory of a different portable Reaper. Works fine now it's in the right place. I have a bug for ya though, coming up in next comment.

**Comment by ScottChesworth** [comment]
Seeing a slight bug here where sometimes the wrong hint, tooltip, whatever you want to call them gets read out. Try this:
1. Go into Preferences, and go to the Device category.
2. Shift+Tab to reach the edit field to specify a block size has focus.
Here, the hint that gets reported is intended to be associated with the "ASIO Configuration" button, next in the tab order.
I'm thinking perhaps that's one for Cockos to tighten up?

**Comment by jcsteh** [comment]
Hopefully fixed in 69c6da43.

**Comment by ScottChesworth** [comment]
That change seems to have silenced the tip for the "Request block size" check box. Unfortunately the issue with the edit field is still present here.

**Comment by jcsteh** [comment]
I don't think there is a tip for request block size. For me, it was
previously reading the tip for the request sample rate option. If I
manually route the mouse and read the tip with obj nav, I see nothing for
the block size options.

To clarify, do you mean you're still getting the ASIO panel tip for request
block size edit?

**Comment by ScottChesworth** [comment]
Yep, still getting the ASIO panel tip for request
block size edit here.

**Comment by jcsteh** [comment]
How fast are you shift+tabbing? If you shift+tab slowly (say, at least a second between each press to be safe), do you still see this? I might have an idea what's happening here, but want to make sure I'm on the right track before I go diving in.

**Comment by ScottChesworth** [comment]
Tabbing or Shift+Tabbing slower does indeed read the right stuff.
