### ISSUE TITLE
OSARA on MacOS with VoiceOver won't speak when REAPER is full screen

### ISSUE THREAD

**Issue by dl7fos** [jcsteh/osara#149]
As I installed OSARA on Windows it works perfectly including the very helpful and necessary speech feedback. On MacOS instaid, the installation process also works fine, files are copying and keymap seems to work also. However, VoiceOver won't speak as I am known by Windows. Is there anything to do? I found nothing about this issue. Maybe I have forgotten to set anything other in VoiceOver? So if I launch me Reaper, I will be informed about version and license information. Pressing the shortcut for OSARA configuration window, it opens up, there is speech output checked.

**Comment by ScottChesworth** [comment]
I'm not much of a Mac user recently so this is just a stab in the
dark, but could this have something to do with notifications?
Apparently strings being spoken by OSARA cause VO's notification sound
to trigger in recent versions of Mac OS, and I've heard a few people
say they've set up a specific VO activity for Reaper with that sound
prompt muted. So, I wonder if perhaps there's also something in VO
utilities that allows you to silence speech notifications as well?

**Comment by dl7fos** [comment]
Yes, that's a good idea. I tweaked some things in VoiceOver to reduce speech output. However, notifications by the system as well as by other apps will be spoken. But I'll give it a try. I just was wondering because of the different documentations nothing was spoken about special VO configs.

**Comment by dl7fos** [comment]
Okay, I checked that out and tried several settings for notifications but nothing happened inside of Reaper. Maybe someone else has this issue?

**Comment by dl7fos** [comment]
Now I found the reason why this occurs. As under Windows, I tried to use Reaper in full screen mode. This accidentally seems to stop OSARA from speaking. However, I found also the problem regarding the beep sounds which could be eliminated by creating a special situation for Reaper inside VO control panel. According to the full screen mode, I don't know if this could be fixed, but it might be helpful to put this issue in the installation documentation or Wiki.

**Comment by ScottChesworth** [comment]
Glad you're up and running. Would be interesting to see if other Mac
users can reproduce this behaviour...

**Comment by GarthHum** [comment]
Having the same experience when using the Reaper action to toggle full screen. 

If the button in the GUI is pressed to go into full screen mode, OSARA seems not affected however if the Reaper action Toggle fullscreen is used, than there is no OSARA feedback until you toggle out of fullscreen. 

On 18 Apr 2018, at 5:12 am, ScottChesworth <notifications@github.com> wrote:

Glad you're up and running. Would be interesting to see if other Mac
users can reproduce this behaviour...

**Comment by marrie** [comment]
I can reproduce this, in fact did last night. I didn't realise that option f111 would tke me into full screen mode. I then lost access to osara in the way of feedback. There is no feedback eiaher when I enter and exit screen mode.

**Comment by kyleman** [comment]
The reaper command is cmd+f11 to toggle full-screen mode. The normal MacOS shortcut ctrl+cmd+f does not work in this case. I'm assuming reaper overrides this some how.
I can confirm that when in full-screen mode osara feedback is lost.
MacOS Mojave 10.14.6
REAPER v6.03/64 rev 881187 (Jan 13 2020)

**Comment by marrie** [comment]
Same with mac os 10.15, I wonder why this is, as this should not be 
possible, but it is. I found this out the hard way last year, or maybe 
it was in 2018, I remember not.

**Comment by GarthHum** [comment]
A bug it maybe, but an exceedingly useful one for me. And officially supported way of muting Osara speech, leaving the screen reader speech intact would be welcome.

Sent from my iPhone

> On 7 Feb 2020, at 2:49 am, Sarah Alawami <notifications@github.com> wrote:
> 

﻿Same with mac os 10.15, I wonder why this is, as this should not be 
possible, but it is. I found this out the hard way last year, or maybe 
it was in 2018, I remember not.

**Comment by parhamdoustdar** [comment]
Thanks for this issue. I was very confused when I lost speech feedback today and finding this issue allowed me to fix it. Thanks!

**Comment by jcsteh** [comment]
Marking as helpWanted because I honestly have no clue why this happens. I guess the Mac a11y notifications posted to mainWindow don't work for some reason when in full screen, but why?

**Comment by ScottChesworth** [comment]
Just had a Mac user confirm that this is resolved in Reaper 6.26.
+ macOS: main window fullscreen button activates REAPER-native fullscreen rather than OS fullscreen

**Comment by pitermach** [comment]
This doesn't seem to be resolved on my end. Tested with latest osara_2021.1pre-493,e9919507, Reaper 6.26 both X64 and ARM64, I'm still seeing the behavior described - going into fullscreen either by pressing the button or pressing Command-F11 causes Osara to stop speaking.

**Comment by TimNoonanVoice** [comment]
Also still a problem pressing Command f11 here too, with same versions.

It gets quite tricky if you press f12 because you then can’t press Command f11 to exit full-screen mode.  to Osara.

Tim


On 1/04/2021, at 3:08 AM, pitermach ***@***.***> wrote:


This doesn't seem to be resolved on my end. Tested with latest osara_2021.1pre-493,e9919507, Reaper 6.26 both X64 and ARM64, I'm still seeing the behavior described - going into fullscreen either by pressing the button or pressing Command-F11 causes Osara to stop speaking.

**Comment by ScottChesworth** [comment]
DOH, guess we're reopening this one then.
@kyleman, which versions of Reaper and OSARA did you test with? Is it still working right for you?

**Comment by kyleman** [comment]
This definitely works for me. How do I find out what version of osara I am running?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pitermach** [comment]
There should be an "Osara: About" action. It doesn't have a key assigned to it by default but F4 should find it. If you don't see it then that's a good indication you're out of date by a fair bit. 

On that note, I just stumbled on something that may give us a clue and could possibly explain why it works for you. For whatever reason, if Reaper is in full screen, and there are no other windows open, you get no speech. But as soon as you open a second Window, like the media explorer, Osara will start speaking again. See if you have any other Reaper windows open either through the VoiceOver window chooser or by pressing command+Accent, close them and check if you have speech then.

I noticed that when you press Command-F11 to bring Reaper in and out of full screen, VoiceOver makes a sound as if the focus just moved to a different window. Could it be that its class or handle is somehow different while Mac Reaper is in full screen, which would cause Osara's messages to not get sent to the right place?

**Comment by kyleman** [comment]
Well, I must have had something else open, because its not talking now. I wonder why two windows open makes a difference?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jcsteh** [comment]
OSARA dispatches announcements to the app's "mainWindow". My guess is that
when REAPER is full screen, that window is null for some reason... or maybe
VoiceOver doesn't listen to that window for some reason in this case. As to
how to fix it, I have no idea; I just don't know enough about Mac GUI
fundamentals, nor do I have the time to figure it out.

**Comment by ScottChesworth** [comment]
I'll try taking this to Cockos later today. Think we've discussed it before, but perhaps the recent change of behaviour will shed some light on what's going on.

**Comment by marrie** [comment]
Try posting your question in the applevis site <http://applevis.com/>   under the development section and see if you get an a answer there. I can’t code worth beans, but that is about all I can suggest. They have really good documentation from apple itself in regard to these things.

**Comment by jcsteh** [comment]
Apple's documentation tends to be really good at the basics, but woefully non-existent once you start getting into more obscure territory like this. Regardless, I had a hunch which turned out to be correct and the issue is now fixed.

**Comment by marrie** [comment]
Nice nice! Glad that little bug has been squashed, I hope?

 

Thanks for  all of this.
